yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name: str = 'posts'
urlpatterns = [
    path('', views.index, name='index'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('group/<slug:slug>/', views.group_posts, name='group_posts'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit')
]

yatube/users/urls.py
from django.contrib.auth.views import (LoginView, LogoutView,
                                       PasswordChangeDoneView,
                                       PasswordChangeView,
                                       PasswordResetCompleteView,
                                       PasswordResetConfirmView,
                                       PasswordResetDoneView,
                                       PasswordResetView)
from django.urls import path

from . import views

app_name: str = 'users'

urlpatterns = [
    path(
        'signup/',
        views.SignUp.as_view(template_name='users/signup.html'),
        name='signup'),
    path(
        'logout/',
        LogoutView.as_view(template_name='users/logged_out.html'),
        name='logout'
    ),
    path(
        'login/',
        LoginView.as_view(template_name='users/login.html'),
        name='login'
    ),
    path(
        'password_change_form/',
        PasswordChangeView.as_view(
            template_name='users/password_change_form.html'
        ),
        name='password_change'
    ),
    path(
        'password_change/done/',
        PasswordChangeDoneView.as_view(
            template_name='users/password_change_done.html'
        ),
        name='password_change_done'
    ),
    path(
        'password_reset/',
        PasswordResetView.as_view(
            template_name='users/password_reset_form.html'
        ),
        name='password_reset'
    ),
    path(
        'password_reset/done/',
        PasswordResetDoneView.as_view(
            template_name='users/password_reset_done.html'
        ),
        name='password_reset_done'
    ),
    path(
        'reset/<uidb64>/<token>/',
        PasswordResetConfirmView.as_view(
            template_name='users/password_reset_confirm.html'
        ),
        name='password_reset_confirm'
    ),
    path(
        'reset/done/',
        PasswordResetCompleteView.as_view(
            template_name='users/password_reset_complete.html'
        ),
        name='password_reset_complete'
    ),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls', namespace='posts')),
    path('group/', include('posts.urls', namespace='posts')),
    path('posts/', include('posts.urls', namespace='posts')),
    path('profile/', include('posts.urls', namespace='posts')),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Group(models.Model):
    """ Class for adding groups on site """
    title = models.CharField(max_length=200, verbose_name='Название группы')
    slug = models.SlugField(unique=True, verbose_name='Вэб адрес')
    description = models.TextField(max_length=600,
                                   verbose_name='Описание группы')

    def __str__(self):
        return self.title


class Post(models.Model):
    """ Class for making posts with given attributes"""
    text = models.TextField(
        verbose_name="Текст поста",
        help_text="Текст нового поста"
    )
    pub_date = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Дата публикации'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор',
    )
    group = models.ForeignKey(
        Group,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        verbose_name='Название группы',
        related_name='posts',
        help_text="Группа, к которой будет относиться пост "
    )

    def __str__(self):
        return self.text[:15]

    class Meta:
        ordering = ['-pub_date']

yatube/posts/forms.py
from django import forms

from .models import Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group')

yatube/users/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

User = get_user_model()


class CreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ('first_name', 'last_name', 'username', 'email')

yatube/about/views.py
from django.views.generic.base import TemplateView


class AboutAuthorView(TemplateView):
    template_name = 'about/author.html'


class AboutTechView(TemplateView):
    template_name = 'about/tech.html'

yatube/posts/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect, render

from .forms import PostForm
from .models import Group, Post, User
from .utilites import use_paginator


def index(request):
    post_list = Post.objects.all()
    page_obj = use_paginator(request, post_list)
    context = {
        'page_obj': page_obj,
    }
    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    post_list = group.posts.all()
    page_obj = use_paginator(request, post_list)
    context = {
        'group': group,
        'page_obj': page_obj,
    }
    return render(request, 'posts/group_list.html', context)


def profile(request, username):
    author = get_object_or_404(User, username=username)
    post_list = author.posts.all()
    page_obj = use_paginator(request, post_list)
    context = {
        'posts': post_list,
        'page_obj': page_obj,
        'author': author
    }
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id: int):
    post = get_object_or_404(Post, pk=post_id)
    context = {
        'post': post
    }
    return render(request, 'posts/post_detail.html', context)


@login_required
def post_create(request):
    form = PostForm(request.POST or None)
    if form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        post.save()
        return redirect("posts:profile", post.author)
    context = {
        "is_edit": False,
        "form": form
    }
    return render(request, 'posts/create_post.html', context)


@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    if request.user != post.author:
        return redirect('posts:post_detail', post_id)
    form = PostForm(request.POST or None, instance=post)
    if form.is_valid():
        form.save()
        return redirect('posts:post_detail', post_id)
    context = {
        "is_edit": True,
        "form": form,
        "post": post
    }
    return render(request, 'posts/create_post.html', context)

yatube/users/views.py
from django.urls import reverse_lazy
from django.views.generic import CreateView

from .forms import CreationForm


class SignUp(CreateView):
    form_class = CreationForm
    success_url = reverse_lazy('posts:index')
    template_name = 'users/signup.html'

yatube/templates/about/author.html
{% extends "base.html" %}
{% block title %}Об авторе проекта{% endblock %}
{% block content %}
<h1>Привет, я - Олег Смагин, я - автор</h1>
<p>
  takoijekakvse@gmail.com <br/>
  https://github.com/OrdinaryWorker
</p>
{% endblock %}

yatube/templates/about/tech.html
{% extends "base.html" %}
{% block title %}Технологии{% endblock %}
{% block content %}
<div class="row" xmlns="http://www.w3.org/1999/html">
  <h2>Использованные технологии</h2>

  <aside class="col-12 col-md-4">
    <ul class="list-group list-group-flush">
      <li class="list-group-item">
        Python
      </li>
      <li class="list-group-item">
        Django
      </li>
      <li class="list-group-item">
        Django ORM
      </li>
      <li class="list-group-item">
        CSS
      </li>
      <li class="list-group-item">
        HTML
      </li>
      <li class="list-group-item">
        VirtualEnvironment
      </li>
      <li class="list-group-item">
        Dev-server
      </li>
      <li class="list-group-item">
        VirtualMailBox
      </li>
    </ul>
  </aside>
  <article class="col-12 col-md-8">
    <p>
      <b> Концепция проекта Yatube </b> </br>
      Yatube - это социальная сеть для публикации личных дневников.
      На которой можно создать свою страницу. Если на нее зайти, то можно
      посмотреть все записи автора. Пользователи могут заходить на чужие
      страницы, подписываться на авторов и комментировать их записи.
    </p>
  </article>
</div>
{% endblock %}

yatube/templates/base.html
<!DOCTYPE html>
<html lang="ru">
  {% load static %}
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="{% static 'img/fav/fav.ico' %}" type="image">
    <link rel="apple-touch-icon" sizes="180x180"
          href="{% static '/fav/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32"
          href="{% static 'img/fav/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16"
          href="{% static 'img/fav/favicon-16x16.png' %}">
    <meta name="msapplication-TileColor" content="#000">
    <meta name="theme-color" content="#ffffff">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <title>
      {% block title %}
        Контент не подвезли
      {% endblock %}
    </title>
  </head>
  <body>
  <header>
    {% include 'includes/header.html' %}
  </header>
  <main>
    <div class="container">
      {% block content %}
        Контент не подвезли
      {% endblock %}
    </div>
  </main>
  <footer>
    {% include 'includes/footer.html' %}
  </footer>
  </body>
</html>

yatube/templates/includes/footer.html
<div class="border-top text-center py-3">
  <p>© {{ year }} Copyright <br> <span style="color:red">Ya</span>tube</p>
</div>

yatube/templates/includes/header.html
{% load static %}
<nav class="navbar navbar-light" style="background-color: lightskyblue">
  <div class="container">
    <a class="navbar-brand" href="{% url 'posts:index' %}">
      <img src="{% static 'img/logo.png' %}" width="30" height="30"
           class="d-inline-block align-top" alt="">
      <span style="color:red">Ya</span>tube</a>
    </a>
    <ul class="nav nav-pills">
      {% with request.resolver_match.view_name as view_name %}
      <li class="nav-item">
        <a class="nav-link {% if view_name  == 'about:author' %}
        active{% endif %}"href="{% url 'about:author' %}">Об авторе</a>
      </li>
      <li class="nav-item">
        <a class="nav-link {% if view_name  == 'about:tech' %}
          active{% endif %}"href="{% url 'about:tech' %}">Технологии</a>
      </li>
      {% if request.user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link {% if view_name  == 'posts:post_create' %}
            active{% endif %}"href="{% url 'posts:post_create' %}">Новая запись
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link link-light"
             href="{% url 'users:password_change' %}">Изменить пароль</a>
        </li>
        <li class="nav-item">
          <a class="nav-link link-light"
             href="{% url 'users:logout' %}">Выйти</a>
        </li>
        <li>
          Пользователь: {{ user.username }}
        </li>
      {% else %}
        <li class="nav-item">
          <a class="nav-link link-light"
             href="{% url 'users:login' %}">Войти</a>
        </li>
        <li class="nav-item">
          <a class="nav-link link-light" href="{% url 'users:signup' %}"
          >Регистрация</a>
        </li>
      {% endif %}
      {% endwith %}
    </ul>
  </div>
</nav>

yatube/templates/posts/create_post.html
{% extends 'base.html' %}
{% block title %}
  {% if is_edit %} Редактирование поста {% else %} Создание поста {% endif %}
{% endblock %}
{% block content %}
  <div class="container py-5">
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">
            {% if is_edit %} Редактировать запись {% else %} Добавить запись
            {% endif %}
          </div>
          <div class="card-body">
            <form method="post"
                    {% if is_edit %}
                  action="{% url 'posts:post_edit' post.pk %}"
                    {% else %}
                  action="{% url 'posts:post_create' %}"
                    {% endif %}>
              {% csrf_token %}
              <div class="form-group row my-3 p-3">
                {% for field in form %}
                  <label for="{{ field.id_for_label }}">
                    {{ field.label }}
                    {% if field.field.required %}
                      <span class="required text-danger">*</span> {% endif %}
                  </label>
                  <div class="form-group row my-3 p-3">
                    {{ field }}
                    <small id="{{ field.id_for_label }}-help"
                           class="form-text text-muted">
                      {{ field.help_text|safe }}
                    </small>
                  </div>
                {% endfor %}
              </div>
              <div class="d-flex justify-content-end">
                <button type="submit" class="btn btn-primary">
                  {% if is_edit %}
                    Сохранить
                  {% else %}
                    Добавить
                  {% endif %}
                </button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

yatube/templates/posts/group_list.html
{% extends "base.html" %}
{% block title %} {{ group.title }} {% endblock %}
{% block content %}
  <h1>{{ group.title }} </h1>
  <p>{{ group.description|linebreaksbr }} </p>
  {% for post in page_obj %}
    <article>
      <ul>
        <li>
          Автор: {{ post.author.get_full_name }}
        </li>
        <li>
          Дата публикации: {{ post.pub_date|date:"d E Y" }}
        </li>
      </ul>
      <p>{{ post.text|linebreaksbr }}</p>
    </article>
    {% if not forloop.last %}
      <hr>{% endif %}
  {% endfor %}
  {% include 'posts/includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/includes/paginator.html
{% if page_obj.has_other_pages %}
<nav aria-label="Page navigation" class="my-5">
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item"><a class="page-link" href="?page=1">Первая</a></li>
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
          Предыдущая
        </a>
      </li>
    {% endif %}
    {% for i in page_obj.paginator.page_range %}
        {% if page_obj.number == i %}
          <li class="page-item active">
            <span class="page-link">{{ i }}</span>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" href="?page={{ i }}">{{ i }}</a>
          </li>
        {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.next_page_number }}">
          Следующая
        </a>
      </li>
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">
          Последняя
        </a>
      </li>
    {% endif %}    
  </ul>
</nav>
{% endif %}

yatube/templates/posts/index.html
{% extends "base.html" %}
{% block title %}Последние обновления на сайте{% endblock %}
{% block content %}
  <h1>Последние обновления на сайте </h1>
  {% for post in page_obj %}
    <article>
      <ul>
        <li>
          Автор: {{ post.author.get_full_name }}
          <a href="{% url 'posts:profile' post.author %}"
          >все записи автора </a>
        </li>
        <li>
          Дата публикации: {{ post.pub_date|date:"d E Y" }}
        </li>
      </ul>
      <p>{{ post.text|truncatewords:100|linebreaksbr }}
        <a href="{% url 'posts:post_detail' post.pk %}"
        > <br> читать полностью </a>
      </p>
      {% if post.group %}
        <a href="{% url 'posts:group_posts' post.group.slug %}"
        >все записи группы </a>
      {% endif %}
      {% if not forloop.last %}
        <hr>{% endif %}
    </article>
  {% endfor %}
  {% include 'posts/includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends "base.html" %}
{% block title %}Пост {{ post.text|truncatechars:30 }}{% endblock %}
{% block content %}
  <div class="row">
    <aside class="col-12 col-md-3">
      <ul class="list-group list-group-flush">
        <li class="list-group-item">
          Дата публикации: {{ post.pub_date|date:"d E Y" }}
        </li>
        {% if post.group %}
          <li class="list-group-item">
            Группа: {{ post.group }}
            <a href="{% url 'posts:group_posts' post.group.slug %}">
              <br> все записи группы
            </a>
          </li>
        {% endif %}
        <li class="list-group-item">
          Автор: {{ post.author.get_full_name }}
          <a href="{% url 'posts:profile' post.author.username %}">
            <br> все посты пользователя
          </a>
        </li>
        <li class="list-group-item d-flex justify-content-between align-items-center">
          Всего постов автора: <span> {{ post_count }}</span>
        </li>
      </ul>
    </aside>
    <article class="col-12 col-md-9">
      <p>
        {{ post.text }}
      </p>
      {% if request.user == post.author %}
          <a class="btn btn-primary"
             href="{% url 'posts:post_edit' post.pk %}">
              редактировать запись
          </a>
      {% endif %}
    </article>
  </div>
  {% include 'posts/includes/../includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/profile.html
{% extends "base.html" %}
{% block title %}
  Профайл пользователя {{ author.get_full_name }}
{% endblock %}
{% block content %}
  <div class="container py-5">
    <h1>Все посты пользователя: {{ author.get_full_name }} </h1>
    <h3>Всего постов: {{ count }} </h3>
    {% for post in page_obj %}
      <article>
        <ul>
          {% if post.group %}
            <li>
              Название группы: {{ post.group }}
            </li>
          {% endif %}
          <li>
            Дата публикации: {{ post.pub_date|date:"d E Y" }}
          </li>
        </ul>
        <p>
          {{ post.text|truncatewords:100|linebreaksbr }}
        <a href="{% url 'posts:post_detail' post.pk %}"> <br>
          читать полностью </a>
        </p>
      </article>
      {% if post.group %}
        <a href="{% url 'posts:group_posts' post.group.slug %}">все записи
        группы</a>
      {% endif %}
      {% if not forloop.last %}
        <hr>
      {% endif %}
    {% endfor %}
    {% include 'posts/includes/paginator.html' %}
  </div>
{% endblock %}

yatube/templates/users/logged_out.html
{# Это код файла templates/users/logged_out.html #}

{% extends 'base.html' %}
{% block title %}Вы вышли из системы{% endblock %}
{% block content %}
<div class="row justify-content-center">
  <div class="col-md-8 p-5">
    <div class="card">
      <div class="card-header">
        Выход
      </div>
      <div class="card-body">
        <p>
          Вы вышли из своей учётной записи. Ждём вас снова!
        </p>
      </div> <!-- card body -->
    </div> <!-- card -->
  </div> <!-- col -->
</div> <!-- row -->
{% endblock %}

yatube/templates/users/login.html
{% extends "base.html" %}
{% block title %}Войти{% endblock %}
{% block content %}
  {% load user_filters %}
  <div class="container py-5">
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">
            Войти на сайт
          </div>
          <div class="card-body">
            <form method="post" action="{% url 'users:login' %}">
              {% csrf_token %}
              <div class="form-group row my-3">
                <label for="id_username">
                  Имя пользователя
                  <span class="required text-danger">*</span>
                </label>
                <input type="text" name="username" autofocus
                       class="form-control"
                       required id="id_username">
              </div>
              <div class="form-group row my-3">
                <label for="id_password">
                  Пароль
                  <span class="required text-danger">*</span>
                </label>
                <input type="password" name="password" class="form-control"
                       required id="id_password">
              </div>
              <div class="col-md-6 offset-md-4">
                <button type="submit" class="btn btn-primary">
                  Войти
                </button>
                <a href="{% url 'users:password_reset' %}"
                   class="btn btn-link">
                  Забыли пароль?
                </a>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

yatube/templates/users/password_change_done.html
{% extends "base.html" %}
{% block title %}Пароль изменён{% endblock %}
{% block content %}
  {% load user_filters %}
  <div class="container py-5">
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">
            Пароль изменён
          </div>
          <div class="card-body">
            <p>Пароль изменён успешно</p>
          </div> <!-- card body -->
        </div> <!-- card -->
      </div> <!-- col -->
    </div> <!-- row -->
  </div>
{% endblock %}

yatube/templates/users/password_change_form.html
{% extends "base.html" %}
{% block title %}Изменение пароля{% endblock %}
{% block content %}
  {% load user_filters %}
  <div class="container py-5">
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">
            Изменить пароль
          </div>
          <div class="card-body">
            <form method="post" action="../users/password_change_form.html">
              <input type="hidden" name="csrfmiddlewaretoken" value="">
              <div class="form-group row my-3 p-3">
                <label for="id_old_password">
                  Старый пароль
                  <span class="required text-danger">*</span>
                </label>
                <input type="password" name="old_password" autofocus
                       class="form-control" required id="id_old_password">
              </div>
              <div class="form-group row my-3 p-3">
                <label for="id_new_password1">
                  Новый пароль
                  <span class="required text-danger">*</span>
                </label>
                <input type="password" name="new_password1" class="form-control"
                       required id="id_new_password1">
                <small id="id_new_password1-help" class="form-text text-muted">
                  <ul>
                    <li>Ваш пароль не должен совпадать с вашим именем или другой
                      персональной информацией или быть слишком похожим на неё.
                    </li>
                    <li>Ваш пароль должен содержать как минимум 8 символов.</li>
                    <li>Ваш пароль не может быть одним из широко распространённых
                      паролей.
                    </li>
                    <li>Ваш пароль не может состоять только из цифр.</li>
                  </ul>
                </small>
              </div>
              <div class="form-group row my-3 p-3">
                <label for="id_new_password2">
                  Подтверждение нового пароля
                  <span class="required text-danger">*</span>
                </label>
                <input type="password" name="new_password2" class="form-control"
                       required id="id_new_password2">
              </div>
              <div class="col-md-6 offset-md-4">
                <button type="submit" class="btn btn-primary">
                  Изменить пароль
                </button>
              </div>
            </form>
          </div> <!-- card body -->
        </div> <!-- card -->
      </div> <!-- col -->
    </div> <!-- row -->
  </div>
{% endblock %}

yatube/templates/users/password_reset_complete.html
{% extends "base.html" %}
{% block title %}Сброс пароля прошёл успешно{% endblock %}
{% block content %}
  {% load user_filters %}
  <div class="container py-5">
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">
            Восстановление пароля завершено
          </div>
          <div class="card-body">
            <p>Ваш пароль был сохранен. Используйте его для входа</p>
            <a href="{% url 'users:login' %}">войти</a>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

yatube/templates/users/password_reset_confirm.html
{% extends "base.html" %}
{% block title %}Новый пароль{% endblock %}
{% block content %}
  {% load user_filters %}
  {% if validlink %}
    <form method="post">
      {% csrf_token %}
      <div class="form-group row my-3 p-3">
        <label for="id_new_password1">
          Новый пароль
          <span class="required text-danger">*</span>
        </label>
        <input type="password" name="new_password1" class="form-control"
               required
               id="id_new_password1">
        <small id="id_new_password1-help" class="form-text text-muted">
          <ul>
            <li>Ваш пароль не должен совпадать с вашим именем или другой
              персональной информацией или быть слишком похожим на неё.
            </li>
            <li>Ваш пароль должен содержать как минимум 8 символов.</li>
            <li>Ваш пароль не может быть одним из широко распространённых
              паролей.
            </li>
            <li>Ваш пароль не может состоять только из цифр.</li>
          </ul>
        </small>
      </div>
      <div class="form-group row my-3 p-3">
        <label for="id_new_password2">
          Подтверждение нового пароля
          <span class="required text-danger">*</span>
        </label>
        <input type="password" name="new_password2" class="form-control"
               required
               id="id_new_password2">
      </div>
      <div class="col-md-6 offset-md-4">
        <button type="submit" class="btn btn-primary">
          Назначить новый пароль
        </button>
      </div>
    </form>
  {% else %}
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">Ошибка</div>
          <div class="card-body">
            <p>Ссылка сброса пароля содержит ошибку или устарела.</p>
          </div> <!-- card body -->
        </div> <!-- card -->
      </div> <!-- col -->
    </div> <!-- row -->
  {% endif %}
{% endblock %}

yatube/templates/users/password_reset_form.html
{% extends "base.html" %}
{% block title %}Сброс пароля{% endblock %}
{% block content %}
  {% load user_filters %}
  <div class="container py-5">
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">
            Чтобы сбросить старый пароль — введите адрес электронной почты, под
            которым вы регистрировались
          </div>
          <div class="card-body">
            <form method="post" action="{% url 'users:password_reset' %}">
              {% csrf_token %}
              <div class="form-group row my-3 p-3">
                <label for="id_email">
                  Адрес электронной почты
                  <span class="required text-danger">*</span>
                </label>
                <input type="email" name="email" maxlength="254"
                       class="form-control" required id="id_email">
              </div>
              <div class="col-md-6 offset-md-4">
                <button type="submit" class="btn btn-primary">
                  Сбросить пароль
                </button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

yatube/templates/users/signup.html
{% extends "base.html" %}
{% block title %}Зарегистрироваться{% endblock %}
{% block content %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">Зарегистрироваться</div>
          <div class="card-body">
          {% load user_filters %} {# Загружаем фильтры #}
              {% if form.errors %}
                  {% for field in form %}
                    {% for error in field.errors %}
                      <div class="alert alert-danger">
                        {{ error|escape }}
                      </div>
                    {% endfor %}
                  {% endfor %}
                  {% for error in form.non_field_errors %}
                    <div class="alert alert-danger">
                      {{ error|escape }}
                    </div>
                  {% endfor %}
              {% endif %}
              <form method="post" action="{% url 'users:signup' %}">
              {% csrf_token %}
              {% for field in form %}
                <div class="form-group row my-3">
                  <label for="{{ field.id_for_label }}">
                    {{ field.label }}
                      {% if field.field.required %}
                        <span class="required text-danger">*</span>
                      {% endif %}
                  </label>
                  {{ field|addclass:'form-control' }}
                    {% if field.help_text %}
                      <small
                         id="{{ field.id_for_label }}-help"
                         class="form-text text-muted"
                      >
                        {{ field.help_text|safe }}
                      </small>
                    {% endif %}
                </div>
              {% endfor %}
              <div class="col-md-6 offset-md-4">
                <button type="submit" class="btn btn-primary">
                  Зарегистрироваться
                </button>
              </div>
            </form>
          </div>
        </div>
      </div>
  </div>
{% endblock %}